### ISSUE TITLE
[Docs] : Testing Readme - Other suggestion - reddit link broken - [r/algorithms]

### ISSUE THREAD

**Issue by vivekdogra02** [trekhleb/promote-your-next-startup#11]
When visiting through the ReadMe (https://github.com/trekhleb/promote-your-next-startup#readme), Under the section - `Other suggestions` - the link for the `r/algorithm` is broken.

It is redirected to the Github 404 try out this link (https://github.com/vivekdogra02/promote-your-next-startup/blob/master/httr/javascriptps:/www.reddit.com/r/algorithms) 

Fixed version
#12

**Comment by trekhleb** [comment]
Fixed in #12
